import { Driver, Route } from "./types";

export const MOCK_DRIVERS: Driver[] = [
  {
    id: "drv-001",
    name: "Emeka Okafor",
    initials: "EO",
    vehicle: "Toyota Hiace",
    plate: "KJA-234AY",
    rating: 4.9,
    trips: 312,
    status: "available",
    eta: 2,
    avatarColor: "#0F6E56",
    routeIds: ["route-001", "route-003"],
    phone: "+234 801 234 5678",
  },
  {
    id: "drv-002",
    name: "Chidi Nwosu",
    initials: "CN",
    vehicle: "Honda Shuttle",
    plate: "LSD-778BD",
    rating: 4.7,
    trips: 198,
    status: "available",
    eta: 5,
    avatarColor: "#993C1D",
    routeIds: ["route-001", "route-002", "route-004"],
    phone: "+234 802 345 6789",
  },
  {
    id: "drv-003",
    name: "Tunde Adeyemi",
    initials: "TA",
    vehicle: "Ford Transit",
    plate: "OG-412CE",
    rating: 4.8,
    trips: 276,
    status: "available",
    eta: 3,
    avatarColor: "#185FA5",
    routeIds: ["route-002", "route-003"],
    phone: "+234 803 456 7890",
  },
  {
    id: "drv-004",
    name: "Amaka Kalu",
    initials: "AK",
    vehicle: "Toyota Hiace",
    plate: "ABS-102FG",
    rating: 5.0,
    trips: 441,
    status: "busy",
    eta: 12,
    avatarColor: "#534AB7",
    routeIds: ["route-001", "route-004"],
    phone: "+234 804 567 8901",
  },
  {
    id: "drv-005",
    name: "Biodun Fasanya",
    initials: "BF",
    vehicle: "Mercedes Sprinter",
    plate: "EKY-881KL",
    rating: 4.6,
    trips: 155,
    status: "available",
    eta: 7,
    avatarColor: "#854F0B",
    routeIds: ["route-003", "route-004"],
    phone: "+234 805 678 9012",
  },
  {
    id: "drv-006",
    name: "Ngozi Eze",
    initials: "NE",
    vehicle: "Hyundai H350",
    plate: "IMO-554PQ",
    rating: 4.8,
    trips: 223,
    status: "offline",
    eta: 0,
    avatarColor: "#3B6D11",
    routeIds: ["route-002"],
    phone: "+234 806 789 0123",
  },
];

export const MOCK_ROUTES: Route[] = [
  {
    id: "route-001",
    name: "Engineering → Main Gate",
    from: "Faculty of Engineering",
    to: "Main Gate",
    stops: ["Engineering Complex", "Admin Block", "Library Junction", "Main Gate"],
    duration: 8,
    fare: 200,
    type: "express",
    schedule: ["7:00 AM", "8:30 AM", "10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM"],
  },
  {
    id: "route-002",
    name: "Engineering → Hostels",
    from: "Faculty of Engineering",
    to: "Student Hostels",
    stops: ["Engineering Complex", "Science Block", "Medical Centre", "Sports Complex", "Student Hostels"],
    duration: 12,
    fare: 150,
    type: "regular",
    schedule: ["7:30 AM", "9:00 AM", "11:00 AM", "1:00 PM", "3:00 PM", "5:30 PM"],
  },
  {
    id: "route-003",
    name: "Engineering → Senate Building",
    from: "Faculty of Engineering",
    to: "Senate Building",
    stops: ["Engineering Complex", "Quad", "Senate Building"],
    duration: 6,
    fare: 180,
    type: "express",
    schedule: ["8:00 AM", "10:00 AM", "12:00 PM", "2:00 PM", "4:00 PM"],
  },
  {
    id: "route-004",
    name: "Engineering → Sports Complex",
    from: "Faculty of Engineering",
    to: "Sports Complex",
    stops: ["Engineering Complex", "Cafeteria", "Social Sciences", "Arts Block", "Medical Centre", "Sports Complex"],
    duration: 15,
    fare: 150,
    type: "evening",
    schedule: ["6:00 PM", "7:00 PM", "8:00 PM", "9:00 PM"],
  },
];
